# Generated by Django 2.2.2 on 2019-06-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='product_added',
        ),
        migrations.AddField(
            model_name='product',
            name='product_added',
            field=models.BooleanField(default=False),
        ),
    ]
