# Generated by Django 2.2.2 on 2019-06-26 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20190626_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category_code',
            field=models.ForeignKey(db_column='category_name', on_delete=django.db.models.deletion.CASCADE, to='shopping.ProductCategory'),
        ),
    ]
